# Methods to create arrays

**.array()
 .ones()
 .zeros()
 .full()
 .empty()**


In [2]:
import numpy as np

In [7]:
a = [1,2,3]
b=np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [8]:
a = [1,2,3, 'a', '5']
b=np.array(a)
print(b)

['1' '2' '3' 'a' '5']


In [13]:
a = [1,2,3, 6.8, '5']
b=np.array(a, dtype=int)
c=np.array(a, dtype=str)

print(b)
print(c)

[1 2 3 6 5]
['1' '2' '3' '6.8' '5']


In [14]:
a = [1,2,3]
b=np.array(a *3)
print(b)

[1 2 3 1 2 3 1 2 3]


In [33]:
one = np.ones(5)
print(one)
one = np.ones(5, dtype=int)
print(one)


zero = np.zeros(5)
print(zero)
zero = np.zeros(5, dtype=int)
print(zero)

[1. 1. 1. 1. 1.]
[1 1 1 1 1]
[0. 0. 0. 0. 0.]
[0 0 0 0 0]


In [32]:
one = np.ones((2,3), dtype = int)
print(one)

[[1 1 1]
 [1 1 1]]


In [38]:
print(np.full(5,3))
print(np.full(5,3, dtype=float))

print()

[3 3 3 3 3]
[3. 3. 3. 3. 3.]


In [3]:
np.empty([2, 2])

array([[2.12199579e-314, 4.67296746e-307],
       [5.37543423e-321, 3.79442416e-321]])

# Assignment

In [6]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(type(a))

<class 'numpy.ndarray'>


In [12]:
a = np.zeros(10, dtype=int)
a[4]=1
print(a)

[0 0 0 0 1 0 0 0 0 0]


# ---------------------------

# More methods to create arrays 

**.arange(start, stop , step)** *start is optional {like range function}*

**.linspace(start, stop , num_of_samples)** *get samples*

**.identity(size)** *identity matrix(NxX)*

**.eye(size(n,m))** *identity matrix(NxM)*

**.random.rand(size)** *random values b/w(0-1)*

In [17]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a = np.arange(5,10)
a


array([5, 6, 7, 8, 9])

In [20]:
a = np.arange(2,10,2)
a

array([2, 4, 6, 8])

In [21]:
a = np.linspace(2,10)
a

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [22]:
a = np.linspace(2,10,5)
a

array([ 2.,  4.,  6.,  8., 10.])

In [23]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [26]:
np.random.rand(3)

array([0.77628742, 0.5189159 , 0.1522808 ])

In [27]:
np.random.rand(2,3)

array([[0.67748291, 0.92835466, 0.75720146],
       [0.47767632, 0.25310337, 0.65226673]])

In [28]:
np.random.rand(10)*10

array([6.4455874 , 6.99443871, 7.88165197, 4.03702966, 9.23868998,
       4.4643208 , 3.33813755, 8.10474646, 3.49424549, 3.10742284])

In [33]:
a = np.random.randint(10)
print(a)
b = np.random.randint(10,20)
print(b)
c = np.random.randint(10,20,5)
print(c)

8
16
[14 19 12 12 14]


In [3]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


# assignment


In [9]:
np.arange(9,50)

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [10]:
np.eye(5,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [12]:
np.linspace(0,5,9)

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

# ---------------------------

# Indexing and Slicing of Arrays

Properties of arrays

collection of pointers which point to 4 diff attriutes

1. **Data**     *Refers to first byte of this array* 
2. **Shape**    *size of arrays*
3. **Dtype**    *data type of the array*
4. **Stride**   *num of bytes to be skipped to get to this array*

In [21]:
a = [1,2,3,4,5]
arr = np.array(a)

print(a)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [22]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)


(5,)
int32
(4,)


In [23]:
a2 = [[1,2,3,4,5],[6,7,8,9,10]]
arr2 = np.array(a2)

print(a2)
print(arr2)

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]
[[1 2 3 4 5]
 [1 2 3 4 5]]


In [24]:
print(arr2.data)
print(arr2.shape)
print(arr2.dtype)
print(arr2.strides)

(2, 5)
int32
(20, 4)


In [32]:
# indexing and slicing

print(a[1:4])
print(arr[1:4])


print(a2[1][4])
print(arr2[1][4])
print(arr2[1,4])

[2, 3, 4]
[2 3 4]
5
5
5


In [42]:
print(a2[1][:3])
print(arr2[1,:3])
print(arr2[:2,2])

[1, 2, 3]
[1 2 3]
[3 3]


# Assignment

In [60]:
x = 1
y = 6
assignment = []

for i in range(4):
    
    assignment.append(np.arange(x,y))
#     print(a)
    x+=5
    y+=5
ass2 =np.array(assignment)
print(ass2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [71]:
print("1->",ass2[2,:3])
print("2->",ass2[1:4,3])
print("3->",ass2[2:4,:6])
print("4->",ass2[1:3,1:3])

1-> [11 12 13]
2-> [ 9 14 19]
3-> [[11 12 13 14 15]
 [16 17 18 19 20]]
4-> [[ 7  8]
 [12 13]]


# ---------------------------

# Mathematical operations on 1D arrays

In [89]:
import numpy as np

li = [1, 2, 3, 4, 5]
a = np.random.randint(1, 20, 5)
b = np.random.randint(1, 20, 5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[ 4  9  7  7 19]
[13  9  8  4 16]


In [80]:
li = [i+1 for i in li]
li

[2, 3, 4, 5, 6]

In [90]:
a+1

array([ 5, 10,  8,  8, 20])

In [91]:
a+b

array([17, 18, 15, 11, 35])

In [92]:
a-b

array([-9,  0, -1,  3,  3])

In [93]:
a*b


array([ 52,  81,  56,  28, 304])

In [94]:
a/b

array([0.30769231, 1.        , 0.875     , 1.75      , 1.1875    ])

In [95]:
a//b

array([0, 1, 0, 1, 1])

In [96]:
a**b

array([  67108864,  387420489,    5764801,       2401, 1637415489])

In [102]:
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin()) #index of min element
print(a.max())
print(a.argmax()) #index of max element

46
9.2
4
0
19
4


In [104]:
print(a)
print(b)

[ 4  9  7  7 19]
[13  9  8  4 16]


In [105]:
a<b

array([ True, False,  True, False, False])

### logical operations

logical_and

logical_or

logical_not

In [109]:
print(np.logical_or(a,b))
print(np.logical_not(a))
print(np.logical_and(a,b))

[ True  True  True  True  True]
[False False False False False]
[False False False False False]


# Boolean Indexing

In [129]:

a = np.array(['t', 'b', 'r', 'd', 'e', 'f', 'z', 'a'])
b = np.random.randint(1, 20, 8)

print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[16 11  5  9 19  2 10  5]


In [130]:
b>10

array([ True,  True, False, False,  True, False, False, False])

In [131]:
bool_arr = b>10
print(bool_arr)
new_arr = b[bool_arr]
print(new_arr)



[ True  True False False  True False False False]
[16 11 19]


In [117]:
new_arr = b[b>10]
print(new_arr)

new_arr = b[(b>10) & (b<18)]
new_arr

[18 13 16 15 19]


array([13, 16, 15])

In [140]:

print(c)
c = b
c[c>15] = 222
c[:3] = 111

print(b)
c

[222  11   5   9 222   2  10   5]
[111 111 111   9 222   2  10   5]


array([111, 111, 111,   9, 222,   2,  10,   5])

In [144]:
ind =np.where(c==111)
print(ind)

print(a[ind])

(array([0, 1, 2], dtype=int64),)
['t' 'b' 'r']


# Assignment


In [145]:
a = np.array([1,2,0,0,4,0])
np.where(a!=0)

(array([0, 1, 4], dtype=int64),)

In [146]:
a = np.array([1,3,5,7,9,11,13,15,17,19])
np.where(a%3==0)

(array([1, 4, 7], dtype=int64),)

In [149]:
a = np.arange(1,11)
a[a%2!=0]=-1
a

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [150]:
a = np.array([11,2,13,4,15,6,27,8,19])
a[a.argmin()] =0
a

array([11,  0, 13,  4, 15,  6, 27,  8, 19])

In [151]:
a = np.arange(1,11)
a[(a>2)&(a<9)]*=-1
a

array([ 1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

In [158]:
b = np.arange(1,21)
a= np.arange(145,165)
print(a)
print(b)

b[np.where(a>155)]

[145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([12, 13, 14, 15, 16, 17, 18, 19, 20])

# ------------------------------------------------------------

# Boolean Indexing in 2d arrays

In [3]:
a = np.random.randint(1, 30, (5, 6))
print(a)

[[24 23 28 19  1 28]
 [20  5 10 20 19 24]
 [18 22 14  9 12 26]
 [18 12 17 29 22 29]
 [ 8 28 18 11 26  5]]


In [7]:
print(a>20)
print("-------")
print(a[a>20])

[[ True  True  True False False  True]
 [False False False False False  True]
 [False  True False False False  True]
 [False False False  True  True  True]
 [False  True False False  True False]]
-------
[24 23 28 28 24 22 26 29 22 29 28 26]


In [9]:
b=a 
b[a>20]=100
print(b)

[[100 100 100  19   1 100]
 [ 20   5  10  20  19 100]
 [ 18 100  14   9  12 100]
 [ 18  12  17 100 100 100]
 [  8 100  18  11 100   5]]


In [13]:
#update value of particular column

bool_arr = b[:,3]==100
print(bool_arr)

[False False False  True False]


In [16]:
b[bool_arr,3] = 1000000
print(b)

[[    100     100     100      19       1     100]
 [     20       5      10      20      19     100]
 [     18     100      14       9      12     100]
 [     18      12      17 1000000     100     100]
 [      8     100      18      11     100       5]]


### assignment


In [18]:
arr = np.array([[21, 20, 19, 18, 17],
                [16, 15, 14, 13, 12],
                [11, 10, 9, 8, 7],
                [6, 5, 4, 3, 2]])
print(arr)

[[21 20 19 18 17]
 [16 15 14 13 12]
 [11 10  9  8  7]
 [ 6  5  4  3  2]]


In [19]:
sorted_indices = arr[:,1].argsort()
sorted_indices

array([3, 2, 1, 0], dtype=int64)

In [27]:
arr[:,1]=arr[sorted_indices, 1]
arr

array([[21, 20, 19, 18, 17],
       [16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2]])

# ------


# Broadcasting

In [1]:
import numpy as np

# (3x3)-(3x3)

x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3,3))
print(x)
print(y)

[[2 6 6]
 [7 1 9]
 [6 1 6]]
[[9 6 6]
 [5 8 8]
 [9 3 1]]


In [2]:
x-y

array([[-7,  0,  0],
       [ 2, -7,  1],
       [-3, -2,  5]])

In [3]:
# (3x3)-(1x3)
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,3)
print(x)
print(y)

[[7 7 2]
 [8 2 2]
 [2 8 8]]
[5 5 6]


In [4]:
x-y


array([[ 2,  2, -4],
       [ 3, -3, -4],
       [-3,  3,  2]])

In [5]:
# (3x2)-(2x3)
x = np.random.randint(1,10,(3,2))
y = np.random.randint(1,10,(2,3))
print(x)
print(y)

[[9 4]
 [2 3]
 [5 2]]
[[6 5 2]
 [8 5 5]]


In [8]:
y=np.transpose(y)
print(y)
x-y

[[6 8]
 [5 5]
 [2 5]]


array([[ 3, -4],
       [-3, -2],
       [ 3, -3]])

In [ ]:
np.resize()
np.reshape()